base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', views.index, name='home'),
    path('create', views.create, name='createtask'),
    path('product', views.product, name='product'),
    path('product_list', views.product_list, name='product_list'),
    path('order', views.order, name='order'),
    path('order_list', views.order_list.as_view(), name ='order_list'),

    path('add_product', views.add_product.as_view(), name='add_product'),
    path('add_product_vk', views.add_product_vk, name='add_product_vk'),
    path('edit_product_vk', views.edit_product_vk, name='edit_product_vk'),

    path('edit_product', views.edit_product, name='edit_product'),
    path('add_product_count', views.add_product_count, name='add_product_count'),
    path('add_product_count_page', views.add_product_count_page, name='add_product_count_page'),
    path('product/<slug:slug>/', views.product_page.as_view(), name='product_page'),
    path('order/<int:pk>/', views.order_page.as_view(), name='order_page'),

    path('order_need_buy/', views.order_need_buy, name='order_need_buy'),

    path('change_order_status', views.change_order_status, name='change_order_status'),
    path('filter_order_status', views.filter_order_status.as_view(), name='filter_order_status'),

    path('search_product_list', views.search_product_list.as_view(), name='search_product_list'),
    path('search_add_product', views.search_add_product.as_view(), name='search_add_product'),
    path('delete_product', views.delete_product, name='delete_product'),

    path('vkgetcode', views.vkgetcode, name='vkgetcode'),
    path('vkgettoken', views.vkgettoken, name='vkgettoken'),

    
    path('budget', views.budget, name='budget'),
    path('change_budget_tag', views.change_budget_tag, name='change_budget_tag'),

]
# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField('Название', max_length=50)
    task = models.TextField('Описание')
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

class Product(models.Model):
	product_id = models.CharField('Номер товара', max_length=5)
	product_name = models.CharField('Название товара', max_length=100)
	product_price = models.FloatField('Закупочная цена', max_length=10)
	product_size = models.CharField('Размер', max_length=15)
	product_count = models.CharField('Доступность', max_length=3, default=0)
	product_image = models.ImageField(upload_to='photos/%Y/%m/%d/')
	uploaded_at = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(product_id)

	def __str__(self):
		return self.product_name

	class Meta:
		verbose_name = 'Товар'
		verbose_name_plural = 'Товары'

class Order(models.Model):
	order_id = models.CharField('Номер заказа', max_length=10)
	order_name = models.CharField('ФИО покупателя', max_length=50)
	order_address = models.CharField('Адрес покупателя', max_length=100)
	order_contain = models.CharField('Содержимое заказа', max_length=100)
	order_status = models.CharField('Статус заказа', max_length=100)

	def __str__(self):
		return self.order_name
    
	class Meta:
		verbose_name = 'Заказ'
		verbose_name_plural = 'Заказы'

class Budget(models.Model):
	TAGS = (
        ('Реклама', 'Реклама'),
        ('Закуп', 'Закуп'),
        ('Торговля', 'Торговля'),
        ('Заказы', 'Заказы'),
        ('Материалы', 'Материалы'),
        ('Раскрутка аккаунтов', 'Раскрутка аккаунтов'),
        )


	budget_name = models.CharField('На что?', max_length=100)
	earn = models.FloatField('Доход/Расход')
	uploaded_at = models.DateTimeField(auto_now_add=True)
	budget_tag = models.CharField(max_length=50, default='null', choices=TAGS)


	class Meta:
		verbose_name = 'Бюджет'
		verbose_name_plural = 'Бюджет'

class Token(models.Model):
	access_token = models.CharField('Токен доступа', max_length=100)

main/forms.py
from .models import Task, Product, Order, Budget
from django.forms import ModelForm, TextInput, Textarea, ImageField, ClearableFileInput, Select


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "task"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название',
            }),
            "task": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание',
            }),
        }
        
class ProductForm(ModelForm):
    class Meta:
        model = Product 
        fields = ["product_id", "product_name", "product_price", "product_size", "product_image"]
        widgets = {
            "product_id": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите номер товара'
            }),
            "product_name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название товара'
            }),
            "product_price": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите закупочную цену'
            }),
            "product_size": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите размер'
            }),
        }

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ["order_id", "order_status", "order_name", "order_address", "order_contain"]
        widgets = {
            "order_id": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите номер заказа', 
            }),
            "order_status": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Статус заказа', 
            }),
            "order_name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите ФИО покупателя', 
            }),
            "order_address": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите адрес покупателя',
            }),
            "order_contain": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите содержание заказа',
            }),
        }

class BudgetForm(ModelForm):
    class Meta:
        model = Budget
        fields = ["budget_name", "earn", "budget_tag"]
        widgets = {
            "budget_name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'На что?',
            }),
            "earn": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Сколько?',
            }),
            "budget_tag": Select(attrs={
                'class': 'custom-select',
            }),
            }

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.db.models import Q
from .models import Task, Product, Order, Budget, Token
from .forms import TaskForm, ProductForm, OrderForm, BudgetForm
from django.views.generic import ListView, DetailView
import requests
import vk
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings

@login_required
def index(request):
	if request.method == 'POST':
		form = BudgetForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
		else:
			error = 'Что-то пошло не так..'

	budget = Budget.objects.all()

	budget_sum = 0

	for item in budget:
		budget_sum += item.earn

	form = BudgetForm()
	context = {
		'form': form,
		'budget': budget,
		'budget_sum': budget_sum,
	}


	return render(request, 'main/index.html', context)

@login_required
def about(LoginRequiredMixin, request):
    return render(request, 'main/about.html')

@login_required
def create(request):
	error = ''
	if request.method == 'POST':
		form = TaskForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('home')
		else:
			error = 'Что-то пошло не так..'

	budget = Budget.objects.all()

	form = TaskForm()
	context = {
		'form': form,
		'error': error,
		'budget': budget,
	}
	return render(request, 'main/create.html', context)

@login_required
def product(request):
	error = ''
	if request.method == 'POST':
		form = ProductForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('home')
		else:
			error = 'Что-то пошло не так..'

	form = ProductForm()
	context = {
		'form': form,
		'error': error,
	}
	return render(request, 'main/product.html', context)

@login_required
def product_list(request):
	products = Product.objects.all()
	return render(request, 'main/product_list.html', {'name': 'Список товаров', 'products': products})

class search_product_list(LoginRequiredMixin, ListView):
	model = Product
	template_name = 'main/search_product_list.html'
	def get_queryset(self):
		query = self.request.GET.get('q')
		print (query)
		a = query
		print (a)
		object_list = Product.objects.filter(Q(product_name__icontains=a) | Q(product_id__icontains=a))
		print (object_list)
		return object_list

class search_add_product(LoginRequiredMixin, ListView):
	model = Product
	template_name = 'main/search_add_product.html'
	def get_queryset(self):
		query = self.request.GET.get('q')
		print (query)
		a = query
		print (a)
		object_list = Product.objects.filter(Q(product_name__icontains=a) | Q(product_id__icontains=a) | Q(product_size__icontains=a))
		print (object_list)
		return object_list

@login_required
def order(request):
	if request.method == 'POST':
		form = OrderForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
		else:
			error = 'Что-то пошло не так..'

	orderform = OrderForm()
	context = {
		'title': 'Создание заказа',
		'orderform': orderform,
	}
	return render(request, 'main/order.html', context)


class order_list(LoginRequiredMixin, ListView):
	model = Order
	template_name = 'main/order_list.html'

class order_page(LoginRequiredMixin, DetailView):
	model = Order
	template_name = 'main/order_page.html'

@login_required
def add_product_count(request):

	add_product_count = request.POST["add_product_count"]
	a = bool(add_product_count)

	if a == False:
		add_product_count = 1
		print ('Сколько нужно добавить?')
		print (add_product_count)
		print ('')

		product_id = request.POST['product_id']

		product_count = request.POST["product_count"]
		print ('Доступность сейчас:')
		print (product_count)
		print ('')

		product_pk = request.POST["product_pk"]
		a = product_pk
		print ('PRODUCT_ID:\n', product_pk)

		product = Product.objects.get(pk=a)
		product_count = product.product_count
		print (product_count)

		a = int(product.product_count)
		b = int(add_product_count)

		c = a + b

		product.product_count = c
		product.save()

		print ('PRODUCT COUNT: ', c)
		product_pk = request.POST["product_pk"]
		url = '/product/' + product_id
		print (url)
		return HttpResponseRedirect(url)

	if a == True:
		print ('Сколько нужно добавить?')
		print (add_product_count)
		print ('')

		product_id = request.POST['product_id']

		product_count = request.POST["product_count"]
		print ('Доступность сейчас:')
		print (product_count)
		print ('')

		product_pk = request.POST["product_pk"]
		a = product_pk
		print ('PRODUCT_ID:\n', product_pk)

		product = Product.objects.get(pk=a)
		product_count = product.product_count
		print (product_count)

		a = int(product.product_count)
		b = int(add_product_count)

		c = a + b

		product.product_count = c
		product.save()

		print ('PRODUCT COUNT: ', c)
		product_pk = request.POST["product_pk"]
		url = '/product/' + product_id
		print (url)
		return HttpResponseRedirect(url)

@login_required
def add_product_count_page(request):

	add_product_count = request.POST["add_product_count"]
	a = bool(add_product_count)

	if a == False:
		add_product_count = 1
		print ('Сколько нужно добавить?')
		print (add_product_count)
		print ('')

		product_count = request.POST["product_count"]
		print ('Доступность сейчас:')
		print (product_count)
		print ('')

		product_id = request.POST['product_id']

		product_pk = request.POST["product_pk"]
		a = product_pk
		print ('PRODUCT_ID:\n', product_pk)

		product = Product.objects.get(pk=a)
		product_count = product.product_count
		print (product_count)

		a = int(product.product_count)
		b = int(add_product_count)

		c = a + b

		product.product_count = c
		product.save()

		print ('PRODUCT COUNT: ', c)
		product_pk = request.POST["product_pk"]
		url = '/product/' + product_id
		print (url)
		return HttpResponseRedirect(url)

	if a == True:
		print ('Сколько нужно добавить?')
		print (add_product_count)
		print ('')

		product_id = request.POST['product_id']

		product_count = request.POST["product_count"]
		print ('Доступность сейчас:')
		print (product_count)
		print ('')

		product_pk = request.POST["product_pk"]
		a = product_pk
		print ('PRODUCT_ID:\n', product_pk)

		product = Product.objects.get(pk=a)
		product_count = product.product_count
		print (product_count)

		a = int(product.product_count)
		b = int(add_product_count)

		c = a + b

		product.product_count = c
		product.save()

		print ('PRODUCT COUNT: ', c)
		product_pk = request.POST["product_pk"]
		url = '/product/' + product_id
		print (url)
		return HttpResponseRedirect(url)

@login_required
def delete_product(request):

	product_id = request.POST["product_id"]
	a = product_id
	print ('PRODUCT_ID:\n', product_id)

	product = Product.objects.get(product_id=a)
	product_count = product.product_count
	print (product)
	product.delete()
	return redirect('add_product')

@login_required
def edit_product(request):
	product_id = request.POST['product_id']
	product_pk = request.POST["product_pk"]
	a = product_pk
	print ('PRODUCT_ID:\n', product_pk)

	product = Product.objects.get(pk=a)
	product_image = product.product_image
	print (product_image)

	c = request.FILES["product_image"]
	product.product_image = c
	product.save()

	print ('PRODUCT COUNT: ', c)
	product_pk = request.POST["product_pk"]
	url = '/product/' + product_id
	print (url)
	return HttpResponseRedirect(url)

@login_required
def change_order_status(request):
	product = Product.objects.get(product_id=1)
	product_image = product.product_image
	order_pk = request.POST["order_pk"]
	new_order_status = request.POST["order_status"]

	print ('Номер заказа:\n', order_pk)
	print ('Новый статус заказа:\n', new_order_status)

	a = order_pk
	order = Order.objects.get(pk=a)
	order_status = order.order_status
	print ('Текущий статус заказа:\n', order_status)

	order.order_status = new_order_status
	order.save()

	return redirect ('order_list')

def order_need_buy(request):
	order_content = request.POST.getlist('order_content')
	print ('ПОЛУЧИЛИ ДАННЫЕ В ТАКОМ ВИДЕ: \n',order_content)
	print (' ')
	order_content_ = []
	for item in order_content:
		content = item.split(" ")
		print (content)
		for el in content:
			order_content_.append(el)
			print ('ДАННЫЕ ПОСЛЕ ПЕРЕРАБОТКИ: ',order_content_)

	order_content = order_content_
	print ('ОКОНЧАТЕЛЬНЫЙ ОРДЕР КОНТЕНТ: ', order_content)

	need_buy = []
	in_stock = []

	for el in order_content:
		print (el)
		product = Product.objects.get(product_id=el)
		product_count = int(product.product_count)
		if product_count == 0:
			need_buy.append(product)
		elif product_count > 0:
			in_stock.append(product)

	print (need_buy)
	print (' ')
	print (' ')
	print (' ')
	print (in_stock)

	context = {
		"need_buy": need_buy,
		'in_stock': in_stock,
	}

	return render(request, 'main/order_need_buy.html', context)


class filter_order_status(ListView):
	model = Order
	template_name = 'main/filter_order_status.html'
	def get_queryset(self):
		queryset = Order.objects.filter(order_status__in=self.request.GET.getlist("qq"))
		return queryset

class product_page(LoginRequiredMixin, DetailView):
	model = Product
	template_name = 'main/product_page.html'

class add_product(LoginRequiredMixin, ListView):
	model = Product
	template_name = 'main/add_product.html'



@login_required
def vkgetcode(request):
	client_id = 7574810
	client_secret = '3gi802fi8D7nB7sgC2m9'
	version = 5.122
	group_id = 197063065
	if request.get_host() == '127.0.0.1:8000':
		redirect_uri = 'http://127.0.0.1:8000/vkgettoken'
	elif request.get_host() == 'shopofsocks.ru':
		redirect_uri = 'http://shopofsocks.ru/vkgettoken'
	scopes = 'market,photos'

	auth_url = 'https://oauth.vk.com/authorize' + '?' + 'client_id=' + str(client_id) + '&display=page&redirect_uri=' + redirect_uri + '&scope=' + scopes + '&response_type=code&v=' + str(version)
	return redirect(auth_url)

@login_required
def vkgettoken(request):
	code = request.GET.get('code')
	print ('КОДДД', code)

main/templates/main/add_product.html
{% extends 'main/main.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}

{% block style %}
table {
	border: 1px solid black;
}
table td, table th{
	width: 150px;
	height: 120px;
	text-align: center;
}
item1 {
	display: flex;
	align-items: center;
}
.item {
	width: 100px;
	height: 100px;
	margin: 10px;
}
.box {
	display: flex;
	text-align: center;
	margin: 2px;
	border-bottom: 1px solid black;
}
.table {
	display: flex;
	justify-content: space-around;
}
.search_input {
	margin-bottom: 10px;
}
.upload_photo_td {
	max-width: 270px;
}
.vk_td {
	max-width: 1000px;
}

{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
<div class='flex'>
	<div class="search_input">
		<form method="get" action="{% url 'search_add_product' %}">
			<input class="form-control" type="text" name="q" placeholder="Найти...">

		</form>
	</div>
    <div>
        <form action="{% url 'vkgetcode' %}" method="post">
            {% csrf_token %}
            <button type='submit' class='btn btn-success'>Получить Token</button>
        </form>
    </div>
</div>
<div class="row">
<div class="table">
<table border="1">
	<tr>
		<th>Номер товара</th>
		<th>Кол-во товара</th>
		<th>Фото</th>
		<th>Пополнить склад</th>
		<th>Добавить в ВК</th>
		<th>Редактировать товар ВК</th>
		<th>Полное удаление товара</th>
	</tr>
{% for Product in object_list %}
	<tr>
	<td>{{ Product.product_id }}</td>
	<td>{{ Product.product_count }}</td>
    <td><a href="{% url 'product_page' Product.slug %}"><img src="/media/{{ Product.product_image }}" width=100 height=100></a>
	<div>{{ Product.product_name }}</div>
    </td>
    <td>
    	<form method="post" action="{% url 'add_product_count' %}">
			{% csrf_token %}
			<input type="hidden" name='product_pk' value='{{ Product.pk }}'>
			<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
			<input type="hidden" name="product_count" value="{{ Product.product_count }}">
			<input type="text" class="form-control" name="add_product_count"> <br>
			<button type="submit" class="btn btn-success">Добавить</button>
		</form>
    </td>
    <td class='vk_td'>
    	<form action="{% url 'add_product_vk' %}" method='post'>
    		{% csrf_token %}
            <input type="hidden" name='access_token' value='{{ access_token }}'>
    		<input type="hidden" name='product_size' value='{{ Product.product_size }}'>
    		<input type="hidden" name='product_pk' value='{{ Product.product_pk }}'>
    		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
    		<input type="hidden" name='product_image' value='{{ Product.product_image }}'>
    		<input type="hidden" name='product_count' value='{{ Product.product_count }}'>
    		<input type="text" name='product_name' class='form-control' placeholder="new name...">
    		<select name='qq' multiple="multiple">
    			<option value="11">Мультики</option>
    			<option value="9">Принты</option>
    			<option value="3">Надписи</option>
    			<option value="10">Рик и Морти</option>
    			<option value="4">Авокадо</option>
    			<option value="12">Nike & Adidas</option>
    		</select><br><br>
    		<button type="submit" class="btn btn-success">Upload</button>
    	</form>
    </td>
    <td>
    	<form action="{% url 'edit_product_vk' %}" method='post'>
    		{% csrf_token %}
    		<input type="hidden" name='product_size' value='{{ Product.product_size }}'>
    		<input type="hidden" name='product_pk' value='{{ Product.product_pk }}'>
    		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
    		<input type="hidden" name='product_image' value='{{ Product.product_image }}'>
    		<input type="hidden" name='product_count' value='{{ Product.product_count }}'>
    		<button type='submit' class='btn btn-success'>Edit</button>
    	</form>
    </td>
    <td>
    	<form action="{% url 'delete_product' %}" method="post">
    		{% csrf_token %}
    		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
    		<button type="submit" class="btn btn-danger">Удалить</button>			    		
    	</form>
    </td>
    </tr>
{% endfor %}
</table>
</div>
</div>





<!-- <form id="myForm">
    Title:   <input name="title" /><br>
    Content: <input name="content" />
</form>
<button id="postBtn">Post</button><br>

<br>
<div id="paramsSent"\>
<div id="return" \>
<script>
$('#postBtn').click(function() {
    var str = $('#myForm').serialize();
    $('#paramsSent').html(str);
    
    $.post('yourPostPath',
          str,
          function(data){
              $('#return').html(data);
          });
 });</script> -->
{% endblock %}

main/templates/main/create.html
{% extends 'main/main.html' %}

{% block title %}
Создание задачи
{% endblock %}

{% block content %}
    <h4>Создание задачи</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        <button type="submit" class="btn btn-success">Добавить</button>
        <span>{{ error }}</span>
    </form>
{% endblock %}

main/templates/main/product_page.html
{% extends 'main/main.html' %}
{% block title %}
Страница товара
{% endblock %}

{% block style %}
tr, td {
	border: 1px solid black;
	text-align: center;
	width: 400px;
	margin: 20px;
}
{% endblock %}

{% block content %}
<table>
	<tr>
	<th>{{ object.product_name }}</th>
	<th>Пополнить склад</th>
	<th>Изменить изображение</th>	
	</tr>
	<tr>
	<td>
		<div class="post-entry">
		<p>ID: {{ object.product_id }}</p>
		В наличии: {{ object.product_count }} <br>
		<br>
		<div>
      		<img src="../../media/{{ object.product_image }}" style="width: 100px">
    	</div>
    </td>
    <td>
		<form method="post" action="{% url 'add_product_count_page' %}">
			{% csrf_token %}
			<input type="hidden" name='product_pk' value='{{ object.pk }}'>
			<input type="hidden" name='product_id' value='{{ object.product_id }}'>
			<input type="hidden" name="product_count" value="{{ object.product_count }}">
			<input type="text" class="form-control" name="add_product_count">
			<button type="submit" class="btn btn-success">Добавить</button>
		</form>
		</div> <br>
	</td>
	<td>
    	<form method="post" enctype="multipart/form-data" action="{% url 'edit_product' %}">
    	{% csrf_token %}
		<input type="hidden" name='product_pk' value='{{ Product.pk }}'>
		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
		<input type="file" name="product_image" accept="image/*" required="" id="id_product_image"> <br>
		<br>
    	<button type="submit" class="btn btn-success">Upload</button>
  		</form>
    	
	</td>
  	</tr>
</table>
{% endblock %}

main/templates/main/search_add_product.html
{% extends 'main/main.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock %}

{% block style %}
table {
	border: 1px solid black;
}
table td, table th{
	width: 150px;
	height: 120px;
	text-align: center;
}
item1 {
	display: flex;
	align-items: center;
}
.item {
	width: 100px;
	height: 100px;
	margin: 10px;
}
.box {
	display: flex;
	text-align: center;
	margin: 2px;
	border-bottom: 1px solid black;
}
.table {
	display: flex;
	justify-content: space-around;
}
.search_input {
	margin-bottom: 10px;
}
{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
	<div class="search_input">
		<form method="get" action="{% url 'search_add_product' %}">
			<input class="form-control" type="text" name="q" placeholder="Найти...">

		</form>
	</div>
<div class="row">
	<div class="table">
	<table border="1">
				<tr>
					<th>Номер товара</th>
					<th>Кол-во товара</th>
					<th>Изображение</th>
					<th>Добавить товар на склад</th>
					<th>Удалить товар полностью</th>
					<th>Редактировать фото</th>
				</tr>
	{% for Product in object_list %}
				<tr>
				<td>{{ Product.product_id }}</td>
				<td>{{ Product.product_count }}</td>
			    <td><a href="{% url 'product_page' Product.pk %}"><img src="/media/{{ Product.product_image }}" width=100 height=100></td></a>
			    <td>
			    	<form method="post" action="{% url 'add_product_count' %}">
						{% csrf_token %}
						<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
						<input type="hidden" name="product_count" value="{{ Product.product_count }}">
						<input type="text" class="form-control" name="add_product_count">
						<button type="submit" class="btn btn-success">Добавить</button>
					</form>
			    </td>
			    <td>
			    	<form action="{% url 'delete_product' %}" method="post">
			    		{% csrf_token %}
			    		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
			    		<button type="submit" class="btn btn-danger">Удалить</button>
			    		<div>{{ Product.product_name }}</div>
			    	</form>
			    </td>
			    <td>
			    	<form method="post" enctype="multipart/form-data" action="{% url 'edit_product' %}">
			    	{% csrf_token %}
			    	<div class="flex ">
			    		<input type="hidden" name='product_pk' value='{{ Product.pk }}'>
			    		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
			<!-- 		<input type="text" name="product_name" class="form-control" placeholder="Введите название товара" maxlength="30" 				required="" id="id_product_name"> 
						<input type="text" name="product_price" class="form-control" placeholder="Введите закупочную цену" required="" id="id_product_price"> 
						<input type="text" name="product_size" class="form-control" placeholder="Введите размер" maxlength="15" required="" id="id_product_size"> -->
					</div>
					<br>
					<input type="file" name="product_image" accept="image/*" required="" id="id_product_image"> <br>
					<br>
			    	<button type="submit" class="btn btn-success">Upload</button>
			  		</form>
			    </td>
			        <td>
    	<form action="{% url 'edit_product_vk' %}" method='post'>
    		{% csrf_token %}
    		<input type="hidden" name='product_size' value='{{ Product.product_size }}'>
    		<input type="hidden" name='product_pk' value='{{ Product.product_pk }}'>
    		<input type="hidden" name='product_id' value='{{ Product.product_id }}'>
    		<input type="hidden" name='product_image' value='{{ Product.product_image }}'>
    		<input type="hidden" name='product_count' value='{{ Product.product_count }}'>
    		<button type='submit' class='btn btn-success'>Edit</button>
    	</form>
    </td>
			    </tr>
	{% endfor %}
	</table>
	</div>
</div>
{% endblock %}